### ISSUE TITLE
Question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [Tornaco/Thanox#811]
My APK scanner just got a few new features, and on today's release of Thanox reported:

    ! repo/github.tornaco.android.thanos_3079783.apk declares sensitive permission(s):
      android.permission.READ_EXTERNAL_STORAGE android.permission.READ_MEDIA_VIDEO
      android.permission.READ_MEDIA_AUDIO android.permission.READ_MEDIA_IMAGES

Some other permissions I was able to identify, but I could not figure what media access is intended for. Could you please clarify? Thanks in advance!

**Comment by Tornaco** [comment]
@IzzySoft Good question, I checked the commit log, it was introduced at 2022/08/24 https://github.com/Tornaco/Thanox/commit/5b3fc1c8a3455cc2c8682b02f69af1bb8a6fbb3a     Adapting to Android storage permissions is too painful; it's very likely that this permission is not necessary. I can take a look in a while.

**Comment by IzzySoft** [comment]
> Adapting to Android storage permissions is too painful

Especially if you want to support Android 4-12+. You could as well choose to spend a day inside a wasps' nest. I still don't know all the exceptions with the multiple combinations of Android's version on-device, minSdk, targetSdk and what directory you want to access. I'm told it gets easier once minSdk is beyond Android 9…

Thanks for checking!

**Comment by IzzySoft** [comment]
As it was reported for today's update again, could you please clarify what they are needed for, so I maybe can establish an exception for them?

![image](https://github.com/Tornaco/Thanox/assets/6781438/813d2fa5-3785-423c-b1a8-b8f119dee135)

As for `DEPENDENCY_INFO_BLOCK`, that can easily be avoided:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

**Comment by Tornaco** [comment]
@IzzySoft Export log, export backup need these permissions

**Comment by IzzySoft** [comment]
Export of logs and backup needs READ on *media* storage? I'd understand `WRITE_EXTERNAL_STORAGE` in this context if `minSdkVersion` would point to Android < 5 (it's Android 7, so you'd rather go with SAF for this). But what audio, video and image files are part of those log and backup files? Maybe I miss something here as I've never used your app.

And while on it, what are the network permissions needed for? I tried checking with the documentation, but unfortunately the [English one](https://tornaco.github.io/Thanox-Docs/en/) isn't English either, apart from the navigation…

**Comment by Tornaco** [comment]
@IzzySoft 

Your understanding is correct. Importing and exporting logs, patches, etc., indeed should not require audio permissions. However, adapting storage permissions for Android can be quite annoying. I remember testing that I had to declare audio AUDIO ... permissions in order to import and export logs, patches, etc. properly[ when adapting to Android T](https://github.com/Tornaco/Thanox/commit/5b3fc1c8a3455cc2c8682b02f69af1bb8a6fbb3a) (33). I don't know why, and I don't want to spend any time researching this annoying SDK design. 

**NETWORK**
Online scene mode rules need to be downloaded online, and Thanox is a paid software that requires network permission to validate the license.

Currently, the documentation is primarily in Chinese, and the English documentation is not yet complete. I'm usually busy with work and don't have much time to devote to translation, so I suggest you try out the Thanox app yourself before asking these questions.

Good luck.

**Comment by IzzySoft** [comment]
Fair enough, thanks! So I'll mark those READ permissions as to be ignored (they'll still shown in chocolate as in above screenshot, but will no longer trigger warnings on updates then), and add a short description on the network permission.

> I suggest you try out the Thanox app yourself before asking these questions.

Apologies for not doing so – but with far more than thousand apps in [my repo](https://apt.izzysoft.de/fdroid) (currently 1.112), I cannot test them all myself.
